# Generated by Django 2.1.7 on 2019-03-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('root_dir', models.CharField(default='frame2/client', max_length=200)),
                ('h5_engine_dir', models.CharField(default='trunk/cocos2d-html5', max_length=200)),
                ('pub_time', models.DateTimeField(verbose_name='time published')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game_dir', models.CharField(default='', max_length=200)),
                ('index_page', models.CharField(default='index.html', max_length=200)),
                ('pub_time', models.DateTimeField(verbose_name='time published')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameTpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('game_dir', models.CharField(default='', max_length=200)),
                ('index_page', models.CharField(default='index.html', max_length=200)),
                ('pub_time', models.DateTimeField(verbose_name='time published')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('host', models.CharField(default='', max_length=200)),
                ('port', models.CharField(default='8088', max_length=200)),
                ('root_dir', models.CharField(default='', max_length=200)),
                ('pub_time', models.DateTimeField(verbose_name='time published')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h5game.Frame')),
            ],
        ),
        migrations.AddField(
            model_name='gametpl',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='h5game.Project'),
        ),
        migrations.AddField(
            model_name='game',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='h5game.Project'),
        ),
        migrations.AddField(
            model_name='game',
            name='template',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='h5game.GameTpl'),
        ),
    ]
