# Generated by Django 2.1.7 on 2019-03-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='host',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='port',
            field=models.CharField(blank=True, default='8088', max_length=200),
        ),
    ]
