# Generated by Django 2.1.7 on 2019-03-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h5game', '0002_auto_20190314_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='GameSkin',
        ),
    ]
