# Generated by Django 2.1.7 on 2019-03-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h5game', '0003_auto_20190314_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameskin',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='h5game.GameTpl'),
        ),
    ]
