# Generated by Django 2.1.7 on 2019-03-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5game', '0004_auto_20190314_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='h5_engine_dir',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_dir',
            field=models.CharField(default='trunk', max_length=200),
        ),
    ]
